[package]
name = "gb_chloro"
version = "0.1.0"
edition = "2021"
default-run = "bootrom"

[lib]
doctest = false

[[bin]]
name = "bootrom"
test = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitflags = "2.3.2"
