[package]
name = "chlorosis_debugger"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chlorosis_core = {path = "../chlorosis_core"}
minifb = "0.24"
native-dialog = "0.6"